from __future__ import annotations

from app.services.chapter_context_support import (
    _compact_arc,
    _compact_value,
    _extract_continuity_bridge,
    _fit_chapter_payload_budget,
    _json_size,
    _load_recent_chapters,
    _normalize_hook,
    _published_and_stock_facts,
    _select_outline_window,
    _serialize_active_interventions,
    _serialize_last_chapter,
    _serialize_novel_context,
    _serialize_recent_summaries,
    _similarity,
    _truncate_list,
    _truncate_text,
    _validate_fact_ledger_state,
)
from app.services.chapter_planning_support import (
    _acquire_generation_slot,
    _arc_remaining,
    _ensure_outline_state,
    _ensure_plan_for_chapter,
    _generate_and_store_pending_arc,
    _load_novel_or_404,
    _persist_generation_failure_snapshot,
    _promote_pending_arc_if_needed,
    _release_generation_slot,
    _save_pipeline_execution_packet,
    _story_bible_payload_to_novel_create,
    _validate_required_planning_docs,
    prepare_next_planning_window,
)
